_target_: src.datamodules.INaturalistEmbContextsDataModuleV2
name: inaturalist_emb_contexts

context_class_size: 50
context_minority_group_proportion: 0.1
query_minority_group_proportion: 0.5

dataset_path: ${oc.env:DATA_ROOT_DIR}/inaturalist2017
encoding_extractor: ${encoding_extractor.name}

train_len: 2000000
eval_len: 1024 # 2^n, because CombinedDataloader removes the last non-full batch

batch_size: 32
num_workers: 4

spurious_setting: ${spurious_setting}  # Use the global value of 'spurious_setting'
sp_token_generation_mode: ${sp_token_generation_mode}  # Use the global value of 'sp_token_generation_mode'

use_context_as_intermediate_queries: ${use_context_as_intermediate_queries}

rotate_encodings: False
n_rotation_matrices: 1000  # 1000 works well, but is slow. Reduce for efficiency when experimenting

label_noise_ratio_interval: null  # [min_ratio, max_ratio], the label noise ratio is uniformly sampled from this interval
input_noise_norm_interval: null  # [min_norm, max_norm], the norm of the Gaussian noise will be uniformly sampled from this interval

permute_input_dim: False

ask_context_prob: null

swapping_minority_proportion_context: 0.1
swapping_minority_proportion_query: 0.5
points_to_swap_range: [50, 100]

val_sets: [inner, inner_outer, outer]  # the order here should match the order in the combined loader
